{
 "title": "Otus Application Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Rate of dialogues send message requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(otus_dialogue_send_message_handled_flow_duration_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Otus Application Dashboard",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(otus_request_handled_flow_duration_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Count of requests with exception",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "otus_request_handled_flow_duration_seconds_count{exception=\"org.springframework.dao.DuplicateKeyException\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests histogram 0.95 quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(otus_request_handled_flow_duration_seconds_bucket[1m])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}