spring:
  application:
    name: otus
  liquibase:
    change-log: ./db/changelog/db.changelog-master.yaml
    enabled: true
    user: user
    password: password
    url: jdbc:mysql://localhost:3306/db
    driver-class-name: com.mysql.cj.jdbc.Driver

  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/db?tlsVersion=TLSv1.2
    username: user
    password: password

logging:
  level:
    org.springframework.data.repository: DEBUG
    org.springframework.r2dbc.r2dbc: DEBUG
    liquibase.logLevel: DEBUG