spring:
  application:
    name: otus
  liquibase:
    change-log: ./db/changelog/db.changelog-master.yaml
    enabled: true
    user: user
    password: password
    url: jdbc:mysql://localhost:3308/db?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver

  r2dbc:
    url: r2dbc:pool:mysql://localhost:3308/db?useSSL=false&allowPublicKeyRetrieval=true
    username: user
    password: password
  datasource:
    url: jdbc:mysql://localhost:3308/db?useSSL=false&allowPublicKeyRetrieval=true
    replicaUrl: jdbc:mysql://localhost:3308/db?useSSL=false&allowPublicKeyRetrieval=true
    username: user
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    org.springframework.data.repository: DEBUG
    org.springframework.r2dbc.r2dbc: TRACE
    liquibase.logLevel: TRACE
    me.kristinasaigak.otus: DEBUG