spring:
  application:
    name: otus
  liquibase:
    change-log: ./db/changelog/db.changelog-master.yaml
    enabled: true
    user: user
    password: password
    url: jdbc:mysql://mysqldb:3306/db?autoReconnect=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver

  r2dbc:
    url: r2dbc:pool:mysql://mysqldb:3306/db?tlsVersion=TLSv1.2
    username: user
    password: password

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    org.springframework.data.repository: TRACE
    org.springframework.r2dbc.r2dbc: TRACE
    liquibase.logLevel: TRACE

