spring:
  application:
    name: otus-app
  liquibase:
    change-log: ./db/changelog/db.changelog-master.yaml
    enabled: true
    user: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true
    driver-class-name: org.postgresql.Driver

  r2dbc:
    url: r2dbc:pool:postgresql://localhost:5432/postgres?tlsVersion=TLSv1.2
    username: postgres
    password: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?useSSL=false&allowPublicKeyRetrieval=true
    replicaUrl: jdbc:postgresql://localhost:15432/postgres?useSSL=false&allowPublicKeyRetrieval=true
    username: postgres
    password: postgres

logging:
  level:
    org.springframework.data.repository: DEBUG
    org.springframework.r2dbc.r2dbc: DEBUG
    liquibase.logLevel: TRACE
    me.kristinasaigak.otus: DEBUG