version: '3.9'

services:
  master_db:
    image: ${POSTGRES_IMAGE}
    container_name: master_db
    volumes:
#      For Windows:
#      - C:\Docker\volumes\master_db:/var/lib/postgresql/data
      - ./db_volume/master_db/:/var/lib/postgresql/data
      - ./db_volume/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports: # <Port exposed> : <Port running inside container>
      - '5432:5432'
    networks:
      - otus_pgnetwork
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $DATABASE

  replica_db_1:
    image: ${POSTGRES_IMAGE}
    container_name: replica_db_1
    depends_on:
      - master_db
    volumes:
      - ./db_volume/replica_db_1/:/var/lib/postgresql/data
    ports:
      - '15432:5432'
    networks:
      - otus_pgnetwork
    environment:
      POSTGRES_PASSWORD: $REPLICATION_POSTGRES_PASSWORD
      POSTGRES_DB: $DATABASE

  replica_db_2:
    image: ${POSTGRES_IMAGE}
    container_name: replica_db_2
    depends_on:
      - master_db
    volumes:
      - ./db_volume/replica_db_2/:/var/lib/postgresql/data
    ports:
      - '25432:5432'
    networks:
      - otus_pgnetwork
    environment:
      POSTGRES_PASSWORD: $REPLICATION_POSTGRES_PASSWORD
      POSTGRES_DB: $DATABASE

  otus-app:
    image: otus-app:latest
    depends_on:
      - master_db
      - replica_db_1
      - replica_db_2
    restart: unless-stopped
    ports:
      - '8080:8080'
    networks:
      - otus_pgnetwork
    environment:
      SPRING_APPLICATION_JSON: '{
               "spring.liquibase.url" : "jdbc:postgresql://master_db:5432/db?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true",
               "spring.datasource.url" : "jdbc:postgresql://master_db:5432/db?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true",
               "spring.r2dbc.url" : "r2dbc:pool:postgresql://master_db/db?tlsVersion=TLSv1.2",
               "spring.datasource.replicaUrl" : "jdbc:postgresql://master_db:5432/db?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true"
             }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - '3333:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - otus_pgnetwork

networks:
  otus_pgnetwork:
    name: otus_pgnetwork
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.19.0.0/16"
