server:
  port: 8083

spring:
  application:
    name: otus-counter-app

  data:
    redis:
      host: redis-server
      port: 6379

logging:
  level:
    me.kristinasaigak.otus: DEBUG

management:
  endpoints:
    enabled-by-default: true
    web.exposure.include: '*'
  endpoint:
    prometheus.enabled: true
    env.enabled: true
    configprops.enabled: true
    info.enabled: true
    loggers.enabled: true
    metrics.enabled: true
    threaddump.enabled: true
    health:
      enabled: true
      show-details: always

